version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mateus
      POSTGRES_PASSWORD: mateus
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mateus@mateusf.com
      PGADMIN_DEFAULT_PASSWORD: mateus
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
